'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ParticleCounter

    '''<summary>
    '''btndaily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btndaily As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnweekly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnweekly As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnrefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnrefresh As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnexport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnexport As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnexportdisabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnexportdisabled As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''dvddldate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvddldate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvPCFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPCFrom As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvPCTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPCTo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsearch As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''hdfPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPeriod As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Pt1Chart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pt1Chart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''hfDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDateTime As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSensor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSensor As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lbl1KNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1KNoData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl10KNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl10KNoData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div1KChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div1KChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lt1kChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lt1kChart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''gv1KAlarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv1KAlarm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dgPCounter_1KAlarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgPCounter_1KAlarm As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''lbl1KEmptyData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1KEmptyData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div10KChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div10KChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lt10kChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lt10kChart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''gv10KAlarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv10KAlarm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dgPCounter_10KAlarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgPCounter_10KAlarm As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''lbl10KEmptyData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl10KEmptyData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProgress As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Progresscontainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Progresscontainer As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''gvPCExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPCExport As Global.System.Web.UI.WebControls.GridView
End Class
