'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TempHum

    '''<summary>
    '''btndaily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btndaily As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnweekly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnweekly As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnrefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnrefresh As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnexport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnexport As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnexportdisabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnexportdisabled As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''dvddldate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvddldate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTempFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTempFrom As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTempTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTempTo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsearch As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''hdfPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPeriod As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblTempNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTempNoData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHumNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHumNoData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divTempChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTempChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ltTempChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltTempChart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''gvTempAlarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTempAlarm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dgTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgTemp As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''lblTempEmptyData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTempEmptyData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProgress As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Progresscontainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Progresscontainer As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''divHumChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHumChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ltHumChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltHumChart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''gvHumAlarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvHumAlarm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dgHum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgHum As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''lblHumEmptyData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHumEmptyData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvTempHumExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTempHumExport As Global.System.Web.UI.WebControls.GridView
End Class
